title: MG.DBP
incoming:
  server:
    prod:
      host: 10.35.16.36
      port: 80
    dev:
      host: localhost
      port: 4040
target:
  base:
    url: http://localhost:4045
  timeout: 5s
  try:
    again:
      retries: 6
      delay: 1s
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      write:
        path: F:\Database\MG-Analytics
      read:
        connectionString: mongodb://localhost:47017
        database: MG-Analytics
cache:
  ignore:
    - /create/
    - /get/new/id
    - /googleLogin
  store:
    prod:
      - memory: true
      - database:
          connectionString: mongodb://localhost:37017
          database: MG-DBP-Cache
display:
  stats:
    every: 1m
