start cmd /k "cd /d D:\Development\Projects\MG3\DBP\Proxy & start.cmd"
start cmd /k "cd /d D:\Development\Projects\MG3\DBP\Node1 & start.cmd"
start cmd /k "cd /d D:\Development\Projects\MG3\Web\Site\Node1 & start.cmd"
start cmd /k "cd /d D:\Development\Projects\MG3\Web\Site\Proxy & start.cmd"
start cmd /k "cd /d D:\Development\Projects\IDE\VueStudio\Web & start.cmd"
