title: MG.Web.Proxy
incoming:
  server:
    prod:
      host: 10.35.16.35
      port: 80
    dev:
      host: localhost
      port: 5050
target:
  base:
    urls:
      # - http://localhost:5055
      - http://localhost:5051
      - http://localhost:5052
  timeout: 5s
  try:
    again:
      retries: 30
      delay: 0.1s
custom:
  - url: /analytics
    status: 404
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      path: F:\Database\MG-Analytics
cache:
  ignore:
    - /_nuxt/
    - /new
    - /api/ip
    - /create
    - /instance/
    - /img/
    - /script/
  store:
    prod:
      # - database:
      #     connectionString: mongodb://localhost:37017
      #     database: MG-Web-Cache
stats:
  every: 1m
log:
  tasks:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'tasks')
  status:
    dev:
      enabled: true
    prod:
      enabled: false
    overwrite: true
    path: (env) => env.getLogPath(env.config.title, 'status')
  debug:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'debug')
  errors:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'errors')
rotate:
  nodes:
    prod: true
    dev: false
process:
  restart:
    periodically:
      from: 00:00
      every: 30m
