params:
  page:
    get: | #ts
      function(url) {
        if (url == "/") return "home";
        if (url == "/admin") return "admin";
        if (url.startsWith("/instance/")) return "instance";
        return "generator";
      }
  urlName:
    get: | #ts
      function(url) {
        if (url.startsWith("/instance/")) return null;
        return url.split("/")[1];
      }
  instanceID:
    get: | #ts
      function(url) {
        if (!url.startsWith("/instance/")) return null;
        return parseInt(url.split("/")[2]);
      }
