params:
  page:
    get: | #ts
      function(url) {
        if (url == "/") return "home";
        if (url == "/test") return "test";
        if (url == "/admin") return "admin";
        if (url.startsWith("/catalog")) return "catalog";
        if (url.startsWith("/b/")) return "builder";
        if (url.startsWith("/t/")) return "thread";
        if (url.startsWith("/m/")) return "thread";
        if (url.startsWith("/instance/")) return "instance";
        if (url.startsWith("/c/")) return "category";
        return "generator";
      }
  urlName:
    get: | #ts
      function(url) {
        if (url == "/") return null;
        if (url == "/admin") return null;
        if (["instance", "t"].some(a => url.startsWith(`/${a}/`))) return null;
        if (["c", "b"].some(a => url.startsWith(`/${a}/`))) return url.split("/")[2];
        return url.split("/")[1];
      }
  threadID:
    get: | #ts
      function(url) {
        if (!url.startsWith("/t/")) return null;
        return parseInt(url.split("/")[2]);
      }
  mediaID:
    get: | #ts
      function(url) {
        if (!url.startsWith("/m/")) return null;
        return parseInt(url.split("/")[2]);
      }
  instanceID:
    get: | #ts
      function(url) {
        if (!url.startsWith("/instance/")) return null;
        return parseInt(url.split("/")[2]);
      }
  url:
    get: | #ts
      function() {
        return window.location.pathname;
      }
