params:
  urlName:
    get: | #ts
      function(url) {
        return "Socially-Awkward-Penguin";
      }

    watch:
      handler: | #ts
        async function(newUrlName) {
          if (!newUrlName) { this.generator = null; return; }
          ;
        }
      immediate: true
data:
  generator:
    watch:
      handler: | #ts
        async function(newGenerator) {
          if (!newGenerator) { this.instances = null; return; }
          await this.dbp.instances.select.popular("en", 0, newGenerator.urlName, { $set: this.instances })
        }
      immediate: true
  instances:
