params:
  urlName:
    get: | #ts
      function(url) {
        return "Socially-Awkward-Penguin";
      }
    watch:
      handler: | #ts
        async function(newUrlName) {
          if (!newUrlName) { this.$root.generator = null; return; }
          await this.$root.dbp.generators.select.one(null, newUrlName, { $set: [this.$root, "generator"] });
        }
      immediate: true
