incoming:
  address:
    host: localhost
    port: 3000
  cors: []
nodes:
  - name: Website 1
    protocol: https
    host: api.memegenerator.net
    port: 443
    enabled: true
  - name: Website 2
    protocol: https
    host: localhost
    port: 80
    enabled: false
sync:
  exclude: [node_modules, config.yaml, nuxt.config.js, .nuxt, dist]
node:
  restart:
    health: 0.5 # Restart the node if the health is below 50%
    timeout: 5 # and it has been unhealthy for N minutes
request:
  timeout: 10 # Timeout requests after 5 seconds
