incoming:
  address:
    host: localhost
    port: 3000
  cors: []
nodes:
  - name: Website 1
    protocol: https
    host: api.memegenerator.net
    port: 443
    enabled: true
  - name: Website 2
    protocol: https
    host: localhost
    port: 80
    enabled: false
