title: MG.DBP.Proxy
incoming:
  server:
    prod:
      host: 10.35.16.36
      port: 80
    dev:
      host: localhost
      port: 4040
target:
  base:
    urls:
      - http://localhost:4050
      - http://localhost:4041
      - http://localhost:4042
  timeout: 1s
  try:
    again:
      retries: 30
      delay: 0s
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      write:
        path: F:\Database\MG-Analytics
      read:
        connectionString: mongodb://localhost:47017
        database: MG-Analytics
cache:
  ignore:
    - /api/Instances/select/popular
    - /create/
    - /get/new/id
    - /googleLogin
  store:
    prod:
      #- memory: true
      - database:
          connectionString: mongodb://localhost:37017
          database: MG-DBP-Cache
      # - database:
      #     path: F:\Database\MG-DBP-Cache
log:
  enabled: true
  path: (env) => env.getLogPath(env.config.title)
stats:
  every: 1m
