title: MG.DBP.Proxy
incoming:
  server:
    prod:
      host: 10.35.16.36
      port: 80
    dev:
      host: localhost
      port: 4040
target:
  base:
    urls:
      prod:
        - http://localhost:4041
        - http://localhost:4042
      dev:
        - https://db.memegenerator.net
  timeout: 5s
  try:
    again:
      retries: 30
      delay: 0.1s
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      write:
        path: F:\Database\MG-Analytics
      read:
        connectionString: mongodb://localhost:47017
        database: MG-Analytics
cache:
  ignore:
    - /api/Threads/
    - /api/Posts/
    - /api/Instances/
    - /create/
    - /sample/
    - /get/new/id
    - /googleLogin
  store:
    prod:
      #- memory: true
      - database:
          connectionString: mongodb://localhost:37017
          database: MG-DBP-Cache
      # - database:
      #     path: F:\Database\MG-DBP-Cache
  queue:
    prod:
      connectionString: mongodb://localhost:37017
      database: MG-DBP-Cache
      collectionName: Queue
log:
  tasks:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'tasks')
  status:
    dev:
      enabled: true
    prod:
      enabled: false
    overwrite: true
    path: (env) => env.getLogPath(env.config.title, 'status')
  debug:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'debug')
  errors:
    dev:
      enabled: true
    prod:
      enabled: false
    path: (env) => env.getLogPath(env.config.title, 'errors')
stats:
  every: 1m
rotate:
  nodes:
    prod: true
    dev: false
process:
  restart:
    periodically:
      from: 00:00
      every: 30m
