title: DatabaseProxy
server:
  host:
    dev: localhost
    prod: 10.35.16.36
  port:
    dev: 3031
    prod: 80
  cors:
    dev: [localhost, localhost:5051]
    prod: [memegenerator.net, vue-studio.com]
  proxy:
    # on dev, we're querying the production database
    # dev: db.memegenerator.net
database:
  connectionString: mongodb://localhost:27017
  query:
    max:
      docs: 50
analytics:
  min:
    elapsed: 50
  database:
    prod:
      path: F:\Database\MG-Analytics
log:
  prod:
    path: (env) => env.getLogPath(env.config.title)
requests:
  severity:
    time: [100, 500, "<"]
dbs:
  IDE:
    users:
      enabled: true
    on:
      user:
        created: | #js
          function(db, dbUser) {
            const newComps = (await db.find("_SavedItems", {
              _id: (new RegExp(`new\.User\.ComponentClass\.`))
            }))
            .map(saved => saved.item);
            for (const newComp of newComps) {
              newComp._id = (await db.getNewID());
              await db.upsert("ComponentClasses", newComp);
            }
            const compIDs = newComps.map(c => c._id);
            dbUser.data.componentClasses._ids.push(...compIDs);
            await db.upsert("Users", dbUser);
          }
  MemeGenerator:
    users:
      enabled: false
restart:
  url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
