title: Scraper
server:
  host: localhost
  port: 3000
article:
  images:
    database:
      path: ../../Database/Images
    folder: ../../Web/images/articles
ynet:
  database:
    path: ../../Database/Ynet
