code-templates:
  http-server: | #ts
    // Create the express app
    const {{varName}} = express();
    {{varName}}.use(express.json());

    {{#each routes}}
    {{../varName}}.get("{{@key}}", (req: any, res: any) => {
      // Handle the route
    });
    {{/each}}

    // Start the server
    {{varName}}.listen({{config.server.port}}, {{config.server.host}});
