title: MG.DBP.2
server:
  port: 4042
process:
  restart:
    periodically:
      from: 01:00
      every: 30m
restart:
  url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
