title: MG.Web
incoming:
  address:
    dev: localhost:5050
    prod: 10.35.16.35:80
  cors: [http://localhost:5050, http://localhost:5051]
  os:
    restart: # memegenerator.net/restart/.. will restart the server
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
  severity:
    time: [100, 500, "<"]
  cache:
    max:
      age: 1m
    ignore:
      - /_nuxt/
      - /new
      - /api/ip
      - /create
    store:
      - memory: true
      - database:
          connectionString: mongodb://localhost:37017
          database: MG-Web-Cache
  request:
    timeout: 5 # Timeout node requests
nodes:
  - name: MG.Website 1
    address: localhost:5051
    process: .\Node1\start.cmd
    restart:
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
  - name: MG.Website 2
    address: localhost:5052
    process: .\Node2\start.cmd
    restart:
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
sync:
  exclude: [node_modules, config.yaml, nuxt.config.js, .nuxt, dist]
node:
  restart:
    enabled: false # Restart the node if it crashes
    health: 0.5 # Restart the node if the health is below 50%
    timeout: 5 # and it has been unhealthy for N minutes
log:
  enabled: true
  path: (env) => env.getLogPath(env.config.title)
  requests:
    min:
      ms: 5000
