title: MG.Web
incoming:
  address:
    dev: localhost:5050
    prod: 10.35.16.35:80
  cors: [http://localhost:5050]
  os:
    restart: # memegenerator.net/restart/.. will restart the server
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
  severity:
    time: [100, 500, "<"]
nodes:
  - name: MG.Website 1
    address: localhost:5051
    process: .\Node1\start.cmd
  - name: MG.Website 2
    address: localhost:5052
    process: .\Node2\start.cmd
sync:
  exclude: [node_modules, config.yaml, nuxt.config.js, .nuxt, dist]
node:
  restart:
    enabled: false # Restart the node if it crashes
    health: 0.5 # Restart the node if the health is below 50%
    timeout: 5 # and it has been unhealthy for N minutes
request:
  timeout: 10 # Timeout requests after 10 seconds
log:
  enabled: true
  path: (env) => env.path.resolve(env.process.cwd(), `${env.config.title}.log`)
  requests:
    min:
      ms: 5000
