server:
  host: localhost
  port: 5052
database:
  content:
    name: MemeGenerator
    connectionString: mongodb://localhost:27017
analytics:
  prod:
    database:
      read:
        connectionString: mongodb://localhost:47017
        database: MG-Analytics
      write:
        path: F:\Database\MG-Analytics
restart:
  url: /api/restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
process:
  restart:
    periodically:
      from: 00:05
      every: 10m
