server:
  host: localhost
  port: 5051
database:
  content:
    name: MemeGenerator
    connectionString: mongodb://localhost:27017
  analytics:
    name: MG-Analytics
    connectionString:
      dev: mongodb://localhost:27017
      prod: mongodb://localhost:47017
