server:
  host: localhost
  port: 5052
database:
  content:
    name: MemeGenerator
    connectionString: mongodb://localhost:27017
  analytics:
process:
  restart:
    periodically:
      from: 01:00
      every: 30m
