title: MG.Web.Proxy
incoming:
  server:
    prod:
      host: 10.35.16.35
      port: 80
    dev:
      host: localhost
      port: 5050
target:
  base:
    urls:
      # - http://localhost:5055
      - http://localhost:5051
      - http://localhost:5052
  timeout: 5s
  try:
    again:
      retries: 6
      delay: 0s
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      path: F:\Database\MG-Analytics
cache:
  ignore:
    - /_nuxt/
    - /new
    - /api/ip
    - /create
  store:
    prod:
      # - database:
      #     connectionString: mongodb://localhost:37017
      #     database: MG-Web-Cache
stats:
  every: 1m
