fourChan:
  boards: [fit]
db:
  fileSystem:
    dataDir: ../Data
  mongo:
    connectionString: mongodb://localhost:27017
    database: AnonymousTimes
images:
  download: true
  take:
    per:
      thread: 5
