title: database.interface
server:
  host: localhost
  port: 5051
project:
  folder: (env) => env.path.resolve(env.process.cwd(), '../Source')
webscript:
  folder: (env) => env.path.join(env.process.cwd(), "../../../Shared/WebScript")
websiteHost:
  folder: (env) => env.path.resolve(env.process.cwd(), '../../WebsiteHost')
static:
  folder: (env) => env.process.cwd()
handler: | #js
  (ctx) => {
    return async (req, res, data) => {
      // Get only the url path, without the query string.
      const url = req.url.split('?')[0];
      if (url == "/api/prompt/to/query") {
        const { entities, prompt } = data;
        const chat = await ctx.ChatOpenAI.new(ctx.Roles.ChatGPT);
        const msg = `these are the entities in my database:
        
        ${JSON.stringify(entities, null, 2)}}
        
        write a MongoDB query to accomplish this task

        reply in this format:
        {
          "query": "...",
          "desc": "...",
          "warning": "..."
          "error": "...""
        }

        ${prompt}`;

        const query = (await chat.send(msg));
        return res.end(JSON.stringify({ query }));
      }
    };
  }
