title: MG.Web
incoming:
  server:
    prod:
      host: 10.35.16.35
      port: 80
    dev:
      host: localhost
      port: 5050
target:
  base:
    url: http://localhost:5055
  timeout: 1s
  try:
    again:
      retries: 30
      delay: 1s
analytics:
  prod:
    api:
      cache:
        database:
          connectionString: mongodb://localhost:37017
          database: MG-Analytics-Cache
    database:
      path: F:\Database\MG-Analytics
cache:
  ignore:
    - /_nuxt/
    - /new
    - /api/ip
    - /create
  store:
    prod:
      - memory: true
      - database:
          connectionString: mongodb://localhost:37017
          database: MG-Web-Cache
display:
  stats:
    every: 1m
