server:
  host: localhost
  port: 5051
database:
  content:
    name: MemeGenerator
    connectionString: mongodb://localhost:27017
  analytics:
    prod:
      path: F:\Database\MG-Analytics
process:
  restart:
    periodically:
      from: 00:00
      every: 1m
