server:
  host: localhost
  port: 5051
database:
  content:
    database: MemeGenerator
    connectionString: mongodb://localhost:27017
  analytics:
    prod:
      read:
        connectionString: mongodb://localhost:47017
        database: MG-Analytics
      write:
        path: F:\Database\MG-Analytics
restart:
  url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
