source:
  database:
    path:
      prod: F:\Database\MG-Analytics
      dev: C:\Database\FileSystem\MG-Analytics
target:
  database:
    connectionString:
      prod: mongodb://localhost:47017
      dev: mongodb://localhost
    database: MG-Analytics
collections: [Events]
