title: MG.DBP
incoming:
  address:
    dev: localhost:4040
    prod: 10.35.16.36:80
  cors: [https://memegenerator.net, https://vue-studio.com, http://localhost]
  severity:
    time: [100, 500, "<"]
  cache:
    dev:
      database:
        path: (env) => env.path.resolve("c:\\Database\\Cache", env.config.title)
    prod:
      database:
        path: (env) => env.path.resolve("f:\\Cache", `${env.config.title}`)
nodes:
  - name: MG.DBP 1
    address: localhost:4041
    process: ./Node1/start.cmd
  - name: MG.DBP 2
    address: localhost:4042
    process: ./Node2/start.cmd
sync:
  exclude: [node_modules, config.yaml, nuxt.config.js, .nuxt, dist]
node:
  restart:
    enabled: false # Restart the node if it crashes
    health: 0.5 # Restart the node if the health is below 50%
    timeout: 5 # and it has been unhealthy for N minutes
request:
  timeout: 10 # Timeout requests after 10 seconds
analytics:
  database:
    prod:
      path: F:\Database\MG-Analytics
log:
  enabled: true
  path: (env) => env.path.resolve(env.process.cwd(), `${env.config.title}.log`)
process:
  restart:
    periodically:
      from: 00:00
      every: 30m
