title:
server:
  host: localhost
  port:
  cors:
    dev: [localhost]
    prod: [memegenerator.net, localhost, localhost:5051]
  # on dev, we're relaying requests to the production dbp/db
  proxy:
database:
  connectionString: mongodb://localhost:27017
  query:
    max:
      docs: 50
analytics:
  min:
    elapsed: 50
  database:
    prod:
      path: F:\Database\MG-Analytics
severity:
  time: [50, 500, "<"]
log:
  path: (env) => env.path.resolve(env.process.cwd(), `..\\`, `${env.config.title}.log`)
requests:
  severity:
    time: [100, 500, "<"]
process:
  restart:
    periodically:
      from: 00:00
      every: 1h
db:
  IDE:
    users:
      enabled: true
  MemeGenerator:
    users:
      enabled: false
