server:
  host: localhost
  port: 3000
database:
  connectionString: mongodb://localhost
  database: MemeGenerator
data:
  set:
    path: (env) => env.path.join(env.process.cwd(), 'Data.Sets', 'instances.jsonl')
