title: Analytics.Api
server:
  host: localhost
  port: 2000
database:
  connectionString: mongodb://localhost:47017
  database: MG-Analytics
cache:
  zero:
    prod:
      database:
        connectionString: mongodb://localhost:37017
        database: MG-Analytics-Cache
debug:
  log:
    enabled: true
    path: (env) => env.getLogPath(env.config.title)
routes:
  - name: default
    path: /
