fourChan:
  boards:
    - biz
  all:
    boards:
      - a
      - c
      - w
      - m
      - cgl
      - cm
      - n
      - jp
      - vt
      - v
      - vg
      - vm
      - vmg
      - vp
      - vr
      - vrpg
      - vst
      - co
      - g
      - tv
      - k
      - o
      - an
      - tg
      - sp
      - xs
      - pw
      - sci
      - his
      - int
      - out
      - toy
      - po
      - p
      - ck
      - lit
      - mu
      - fa
      - "3"
      - gd
      - diy
      - wsg
      - qst
      - biz
      - trv
      - fit
      - x
      - adv
      - lgbt
      - mlp
      - news
      - wsr
      - vip
db:
  fileSystem:
    dataDir: ../Data
  mongo:
    connection: mongodb://localhost:27017
    database: FourChan
images:
  download: false
  take:
    per:
      thread: 5
