title: MG.Web
incoming:
  address: localhost:5055
  cors: [http://localhost:5055, http://localhost:5050, http://localhost:5051]
  os:
    restart: # memegenerator.net/restart/.. will restart the server
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
  severity:
    time: [100, 500, "<"]
  cache:
    max:
      age: 1m
    ignore:
      - /_nuxt/
      - /new
      - /api/ip
      - /create
    store:
      - database:
          path: F:\Database\MG-Web-Cache
      # - database:
      #     connectionString: mongodb://localhost:37017
      #     database: MG-Web-Cache
  request:
    timeout: 1 # Timeout node requests
  analytics:
    prod:
      api:
        cache:
          zero:
            database:
              connectionString: mongodb://localhost:37017
              database: MG-Analytics-Cache
      database:
        write:
          path: F:\Database\MG-Analytics
        read:
          connectionString: mongodb://localhost:47017
          database: MG-Analytics
nodes:
  - name: MG.Website 1
    address: localhost:5051
    process: .\Node1\start.cmd
    restart:
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
  - name: MG.Website 2
    address: localhost:5052
    process: .\Node2\start.cmd
    restart:
      url: /restart/Jz0xnwG1bDv57LFpKTS6UkV8h9XQtCeBOMl2NHfRIj3yPcZYimAsrqdV4oWEaFhu
sync:
  exclude: [node_modules, config.yaml, nuxt.config.js, .nuxt, dist]
node:
  restart:
    enabled: false # Restart the node if it crashes
    health: 0.5 # Restart the node if the health is below 50%
    timeout: 5 # and it has been unhealthy for N minutes
log:
  enabled: true
  path: (env) => env.getLogPath(env.config.title)
  requests:
    min:
      ms: 5000
process:
  restart:
    periodically:
      from: 00:00
      every: 10m
