server:
  host: localhost
project:
  folder: (env) => env.path.resolve(env.process.cwd(), '../../../Source')
webscript:
  folder: (env) => env.path.join(env.process.cwd(), "../../../../../Shared/WebScript")
websiteHost:
  folder: (env) => env.path.resolve(env.process.cwd(), '../../../../WebsiteHost')
static:
  folder: (env) => env.process.cwd()
analytics:
  prod:
    database:
      path: F:\Database\MG-Analytics
  dev:
    database:
