title: MG.Web.Images
server:
  host: 10.35.16.37
  port: 80
old:
  images:
    server: http://jsonvisualizer.net
folders:
  images:
    dev: C:\eff\Development\Temp
    prod: F:\MemeGenerator\Images
database:
  connectionString: mongodb://localhost
  database: MemeGenerator
severity:
  time: [400, 800, "<"]
log:
  debug:
    enabled: true
    path: (env) => env.getLogPath(env.config.title, 'debug')
  errors:
    enabled: true
    path: (env) => env.getLogPath(env.config.title, 'errors')
