server:
  host: 10.35.16.37
  port: 80
old:
  images:
    server: http://10.35.16.2:8080
folders:
  images:
    dev: C:\eff\Development\Temp
    prod: F:\MemeGenerator\Images
database:
  connectionString: mongodb://localhost
  database: MemeGenerator
